# Data
path: C:\Users\boqua\ProjetM1\PoseEstimationFeatures\Personne_qui_marche\data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [18, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14, 17, 16]

# Classes
names:
  0: human
